stages:
  preprocess:
    cmd: python task1-EDA/src/data_processing.py
    deps:
    - data/raw/insurance_claims.csv
    - task1-EDA/src/data_processing.py
    outs:
    - data/processed/processed_insurance_data.csv
    params:
    - preprocess
  feature_engineering:
    cmd: python task1/src/modeling.py
    deps:
    - data/processed/processed_insurance_data.csv
    - task1/src/modeling.py
    outs:
    - data/outputs/predictions.csv
    params:
    - config/feature_params.yaml

  evaluate:
    cmd: python task1/src/reporting.py
    deps:
    - data/outputs/predictions.csv
    - task1/src/reporting.py
    metrics:
    - reports/evaluation_metrics.json
