stages:
  preprocess:
    cmd: python task1-EDA/src/data_processing.py
    deps:
      - task1-EDA/src/data_processing.py
      - data/raw/insurance_claims.csv
      - params.yaml
    outs:
      - data/processed/processed_insurance_data.csv
    params:
      - preprocess

  feature_engineering:
    cmd: python task1-EDA/src/modeling.py
    deps:
      - task1-EDA/src/modeling.py
      - data/processed/processed_insurance_data.csv
      - params.yaml
    outs:
      - data/outputs/predictions.csv
    metrics:
      - reports/evaluation_metrics.json:
          cache: false