preprocess:
  input_file: "data/raw/insurance_claims.csv"
  output_file: "data/processed/processed_insurance_data.csv"
  test_split: 0.2
  random_state: 42

feature_engineering:
  input_file: "data/processed/processed_insurance_data.csv"
  output_file: "data/outputs/predictions.csv"
  features: ["totalpremium", "totalclaims", "loss_ratio"]
  target: "totalclaims"
  test_size: 0.2
  random_state: 42
  imputation_strategy: "iterative"  # Added new parameter

model:
  type: xgboost
  n_estimators: 100
  max_depth: 6
  learning_rate: 0.1
  objective: "reg:squarederror"