# task2-DVC/config/feature_params.yaml
input_file: "data/processed/processed_insurance_data.csv"
output_file: "data/outputs/predictions.csv"
features:
  - totalpremium
  - totalclaims
  - loss_ratio
